package com.texttosql.util;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.springframework.stereotype.Component;

import com.texttosql.domain.GeneratedSQL;
import com.texttosql.domain.QueryRequest;
import com.texttosql.domain.RelevantTables;
import com.texttosql.domain.TableMetadata;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Component
public class ResponseParser {
    /**
     * Parse table identification response from LLM
     */
    public RelevantTables parseTableResponse(String llmResponse, QueryRequest request) {
        List<String> tableNames = new ArrayList<>();
        
        // Try to extract table names from response
        for (TableMetadata table : request.getSchema().getTables()) {
            String fullName = table.getFullTableName();
            if (llmResponse.toLowerCase().contains(fullName.toLowerCase())) {
                tableNames.add(fullName);
            }
        }

        // Fallback: use all tables
        if (tableNames.isEmpty()) {
            log.warn("⚠️ Could not parse table names, using all tables");
            for (TableMetadata table : request.getSchema().getTables()) {
                tableNames.add(table.getFullTableName());
            }
        }

        return RelevantTables.builder()
            .tableNames(tableNames)
            .reasoning("Extracted from LLM response")
            .originalRequest(request)
            .build();
    }


    /**
     * Parse SQL generation response from LLM
     */
    public GeneratedSQL parseSQLResponse(String llmResponse, RelevantTables tables) {
        String sql = extractSQL(llmResponse);
        
        // Fallback if no valid SQL found
        if (sql == null || sql.trim().isEmpty()) {
            log.warn("⚠️ LLM response parsing failed, using fallback query");
            sql = "SELECT * FROM " + tables.getTableNames().get(0) + " LIMIT 500";
        }
        
        return GeneratedSQL.builder()
            .sqlQuery(sql)
            .explanation("Generated by LLM")
            .relevantTables(tables)
            .build();
    }

    /**
     * Extract SQL from various LLM response formats
     */
    private String extractSQL(String llmResponse) {
        // Method 1: Look for SELECT ... LIMIT pattern
        Pattern selectPattern = Pattern.compile(
            "(SELECT\\s+.+?LIMIT\\s+\\d+)", 
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL
        );
        Matcher matcher = selectPattern.matcher(llmResponse);
        if (matcher.find()) {
            return cleanSQL(matcher.group(1));
        }
        
        // Method 2: Look for any SELECT statement
        Pattern anySelectPattern = Pattern.compile(
            "(SELECT\\s+.+?(?:;|$))", 
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL
        );
        matcher = anySelectPattern.matcher(llmResponse);
        if (matcher.find()) {
            String sql = cleanSQL(matcher.group(1));
            // Add LIMIT if missing
            if (!sql.toUpperCase().contains("LIMIT")) {
                sql += " LIMIT 500";
            }
            return sql;
        }
        
        // Method 3: Look for SQL: prefix
        if (llmResponse.contains("SQL:")) {
            String afterSQL = llmResponse.substring(llmResponse.indexOf("SQL:") + 4).trim();
            String[] lines = afterSQL.split("\n");
            if (lines.length > 0) {
                return cleanSQL(lines[0]);
            }
        }
        
        // Method 4: Just look for "SELECT" anywhere
        if (llmResponse.toUpperCase().contains("SELECT")) {
            int selectIndex = llmResponse.toUpperCase().indexOf("SELECT");
            String fromSelect = llmResponse.substring(selectIndex);
            // Take until semicolon or end
            int endIndex = fromSelect.indexOf(';');
            if (endIndex > 0) {
                fromSelect = fromSelect.substring(0, endIndex);
            }
            return cleanSQL(fromSelect) + " LIMIT 500";
        }
        
        return null;
    }

    /**
     * Clean SQL string
     */
    private String cleanSQL(String sql) {
        return sql.trim()
            .replaceAll("\\s+", " ")  // Normalize whitespace
            .replaceAll(";$", "")      // Remove trailing semicolon
            .trim();
    }
}
